### PR TITLE
Fix payment step crash due to responsive-layout

### PR DESCRIPTION
**Pull request by lucasecdb**
#### What problem is this solving?

This PR fixes an issue in the Payment step that occurred when you resized the window from desktop -> mobile -> desktop. The error is because of a library in the `CreditCard` component inside the payment which is being used to communicate with the credit card `iframe` based on events built on top of `window.postMessage`.

The library has a restriction that only one event must exist at a time (e.g. you can't listen to, say, `paymentSystems` twice) and _apparently_ our `CreditCard` component was being rendered twice 😱 which caused us to listen to the same event as the other component instance, so the library throwed an error when the second instance begin rendering.

So, it turns out that the issue wasn't with our component, but with the `responsive-layout` component from the SF team. This layout component is built on top of the `device-detector` app, and each block of this app (`responsive-layout.desktop`, `responsive-layout.mobile`, etc) used a _separate_ "instance" of the hook exposed in `device-detector`. So, when you changed the resolution of the page, each component received its own event to update itself causing for a brief moment for both components we use (desktop and mobile) to be mounted in the page (see screenshot below), and causing the error I described above.

image

#### How should this be manually tested?

[Workspace](https://lucas--checkoutio.myvtex.com/cart/add?sku=289). You can see the issue in [this workspace](https://chkio--checkoutio.myvtex.com/cart/add?sku=289).

Test plan:

1. Proceed to checkout and fill all informations until the payment step
2. Resize the screen from desktop to mobile, then to desktop again.
3. The page shouldn't crash.

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

payment-resize

#### Type of changes

✔️ | Type of Change
---|---
✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Review by pedromtec — COMMENTED** [review]
The app is breaking. Error: `TypeError: Cannot read property 'map' of undefined`
Did you link this [branch](https://github.com/vtex-apps/order-payment/pull/7)  ?

**Comment by lucasecdb** [comment]
@pedromtec which app and which workspace? It doesn't seem to reproduce here.

**Comment by pedromtec** [comment]
> @pedromtec which app and which workspace? It doesn't seem to reproduce here.

I added other item and it worked '-'

**Review by pedromtec — APPROVED** [review]
It worked. LGTM

**Review by marcoskwkm — APPROVED** [review]
Interesting bug.

**Pull request merged**
