### PR TITLE
Fix design issues

### PR DESCRIPTION
**Pull request by lucasecdb**
#### What problem is this solving?
Fix most design issues reported in Figma. In this PR I didn't fix the issue about the breakpoint of the drawer, because the breakpoint we are using is defined in the [`vtex.responsive-layout`](https://github.com/vtex-apps/responsive-layout) app, so we will most probably open an issue there to solve this. Depends on vtex-apps/checkout-summary#29

[Related clubhouse story](https://app.clubhouse.io/vtex/story/34395/corre%C3%A7%C3%A3o-de-inconsistencias-de-design-no-checkout)

#### How should this be manually tested?
[Workspace](https://chkio--checkoutio.myvtex.com/checkout/#/)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [x] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

### Desktop

image

Most noticeable changes:

- Ratio between width of checkout/summary has been changed from 66%/33% to 60%/40%.
- Left padding of the items summary has been fixed.
- Added a disclaimer in the footer.

### Tablet/Large mobile

Most noticeable changes:

- Fixed alignment of the "View Cart" button. Now it is aligned properly with the right margin of the container.
- Top padding of the footer has been fixed. All of the text is now aligned with the top of the flexbox used.
- Left and right padding of the footer is also respecting the margin of the page container now.

### Phone/Small mobile

Most noticeable changes:

- Font size and weight of the steps titles are now fixed.
- Added a button to open the cart drawer in summary.

#### Type of changes

✔️ | Type of Change
---|---
✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Comment by darlenedms** [comment]
Since this PR is dedicated to fix design issues, would be nice to have some screenshots. Even reading the issue on Clubhouse it wasn't clear what I should be seeing...

**Comment by lucasecdb** [comment]
@darlenedms sorry about that! I thought about including the screenshots here but I didn't wanted to clutter the PR description. but I could if you want :-)

**Comment by darlenedms** [comment]
Please do, otherwise only @davicosta99 will be able to review the result. 🎨

**Review by jeffersontuc — DISMISSED** [review]

**Comment by lucasecdb** [comment]
@darlenedms I updated the PR description, and added a few point bellow each screenshot to highlight the most noticeable changes.

I still need to add the "View Cart" button next to the "Summary" title before merging this though.

**Review by darlenedms — APPROVED** [review]
🖌

**Review by thiagomurakami — APPROVED** [review]
LGTM

Also, I think a before and after in the PR description also helps the reviewer!

**Pull request merged**
